name: Deploy to VPS Servers

on:
  push:
    branches:
      - main # or the branch you want to trigger the action on

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # goldbetio.com

      - name: Deploy to 185.206.180.88 - PRIMA
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_PRIMA }}
          username: ${{ secrets.FTP_USER_PRIMA }}
          password: ${{ secrets.FTP_PASSWORD_PRIMA }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbetio.com/ # The directory on the server where you want to upload the dist folder

      - name: Deploy to VPS 194.164.235.224 - Hostkey
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_HOSTKEY }}
          username: ${{ secrets.FTP_USER_HOSTKEY }}
          password: ${{ secrets.FTP_PASSWORD_HOSTKEY }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbetio.com/ # The directory on the server where you want to upload the dist folder

      - name: Deploy to VPS 148.113.44.74 - OVH
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_OVH }}
          username: ${{ secrets.FTP_USER_OVH }}
          password: ${{ secrets.FTP_PASSWORD_OVH }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbetio.com/ # The directory on the server where you want to upload the dist folder

      # goldbet.wiki

      - name: Deploy to 185.206.180.88 - PRIMA
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_PRIMA }}
          username: ${{ secrets.FTP_USER_PRIMA }}
          password: ${{ secrets.FTP_PASSWORD_PRIMA }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.wiki/ # The directory on the server where you want to upload the dist folder

      - name: Deploy to VPS 194.164.235.224 - Hostkey
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_HOSTKEY }}
          username: ${{ secrets.FTP_USER_HOSTKEY }}
          password: ${{ secrets.FTP_PASSWORD_HOSTKEY }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.wiki/ # The directory on the server where you want to upload the dist folder

      - name: Deploy to VPS 148.113.44.74 - OVH
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_OVH }}
          username: ${{ secrets.FTP_USER_OVH }}
          password: ${{ secrets.FTP_PASSWORD_OVH }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.wiki/ # The directory on the server where you want to upload the dist folder

      # goldbet.website

      - name: Deploy to 185.206.180.88 - PRIMA
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_PRIMA }}
          username: ${{ secrets.FTP_USER_PRIMA }}
          password: ${{ secrets.FTP_PASSWORD_PRIMA }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.website/ # The directory on the server where you want to upload the dist folder

      - name: Deploy to VPS 194.164.235.224 - Hostkey
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_HOSTKEY }}
          username: ${{ secrets.FTP_USER_HOSTKEY }}
          password: ${{ secrets.FTP_PASSWORD_HOSTKEY }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.website/ # The directory on the server where you want to upload the dist folder

      - name: Deploy to VPS 148.113.44.74 - OVH
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_OVH }}
          username: ${{ secrets.FTP_USER_OVH }}
          password: ${{ secrets.FTP_PASSWORD_OVH }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.website/ # The directory on the server where you want to upload the dist folder

      # goldbet.sbs

      - name: Deploy to 185.206.180.88 - PRIMA
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_PRIMA }}
          username: ${{ secrets.FTP_USER_PRIMA }}
          password: ${{ secrets.FTP_PASSWORD_PRIMA }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.sbs/ # The directory on the server where you want to upload the dist folder

      - name: Deploy to VPS 194.164.235.224 - Hostkey
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_HOSTKEY }}
          username: ${{ secrets.FTP_USER_HOSTKEY }}
          password: ${{ secrets.FTP_PASSWORD_HOSTKEY }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.sbs/ # The directory on the server where you want to upload the dist folder

      - name: Deploy to VPS 148.113.44.74 - OVH
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_OVH }}
          username: ${{ secrets.FTP_USER_OVH }}
          password: ${{ secrets.FTP_PASSWORD_OVH }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.sbs/ # The directory on the server where you want to upload the dist folder

      # goldbet.monster

      - name: Deploy to 185.206.180.88 - PRIMA
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_PRIMA }}
          username: ${{ secrets.FTP_USER_PRIMA }}
          password: ${{ secrets.FTP_PASSWORD_PRIMA }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.monster/ # The directory on the server where you want to upload the dist folder

      - name: Deploy to VPS 194.164.235.224 - Hostkey
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_HOSTKEY }}
          username: ${{ secrets.FTP_USER_HOSTKEY }}
          password: ${{ secrets.FTP_PASSWORD_HOSTKEY }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.monster/ # The directory on the server where you want to upload the dist folder

      - name: Deploy to VPS 148.113.44.74 - OVH
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_OVH }}
          username: ${{ secrets.FTP_USER_OVH }}
          password: ${{ secrets.FTP_PASSWORD_OVH }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.monster/ # The directory on the server where you want to upload the dist folder

      # goldbet.lol

      - name: Deploy to 185.206.180.88 - PRIMA
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_PRIMA }}
          username: ${{ secrets.FTP_USER_PRIMA }}
          password: ${{ secrets.FTP_PASSWORD_PRIMA }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.lol/ # The directory on the server where you want to upload the dist folder

      - name: Deploy to VPS 194.164.235.224 - Hostkey
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_HOSTKEY }}
          username: ${{ secrets.FTP_USER_HOSTKEY }}
          password: ${{ secrets.FTP_PASSWORD_HOSTKEY }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.lol/ # The directory on the server where you want to upload the dist folder

      - name: Deploy to VPS 148.113.44.74 - OVH
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_OVH }}
          username: ${{ secrets.FTP_USER_OVH }}
          password: ${{ secrets.FTP_PASSWORD_OVH }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.lol/ # The directory on the server where you want to upload the dist folder

      # goldbet.cam

      - name: Deploy to 185.206.180.88 - PRIMA
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_PRIMA }}
          username: ${{ secrets.FTP_USER_PRIMA }}
          password: ${{ secrets.FTP_PASSWORD_PRIMA }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.cam/ # The directory on the server where you want to upload the dist folder

      - name: Deploy to VPS 194.164.235.224 - Hostkey
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_HOSTKEY }}
          username: ${{ secrets.FTP_USER_HOSTKEY }}
          password: ${{ secrets.FTP_PASSWORD_HOSTKEY }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.cam/ # The directory on the server where you want to upload the dist folder

      - name: Deploy to VPS 148.113.44.74 - OVH
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_OVH }}
          username: ${{ secrets.FTP_USER_OVH }}
          password: ${{ secrets.FTP_PASSWORD_OVH }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.cam/ # The directory on the server where you want to upload the dist folder

      # goldbet.cfd

      - name: Deploy to 185.206.180.88 - PRIMA
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_PRIMA }}
          username: ${{ secrets.FTP_USER_PRIMA }}
          password: ${{ secrets.FTP_PASSWORD_PRIMA }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.cfd/ # The directory on the server where you want to upload the dist folder

      - name: Deploy to VPS 194.164.235.224 - Hostkey
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_HOSTKEY }}
          username: ${{ secrets.FTP_USER_HOSTKEY }}
          password: ${{ secrets.FTP_PASSWORD_HOSTKEY }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.cfd/ # The directory on the server where you want to upload the dist folder

      - name: Deploy to VPS 148.113.44.74 - OVH
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_OVH }}
          username: ${{ secrets.FTP_USER_OVH }}
          password: ${{ secrets.FTP_PASSWORD_OVH }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.cfd/ # The directory on the server where you want to upload the dist folder

      # goldbet.click

      - name: Deploy to 185.206.180.88 - PRIMA
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_PRIMA }}
          username: ${{ secrets.FTP_USER_PRIMA }}
          password: ${{ secrets.FTP_PASSWORD_PRIMA }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.click/ # The directory on the server where you want to upload the dist folder

      - name: Deploy to VPS 194.164.235.224 - Hostkey
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_HOSTKEY }}
          username: ${{ secrets.FTP_USER_HOSTKEY }}
          password: ${{ secrets.FTP_PASSWORD_HOSTKEY }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.click/ # The directory on the server where you want to upload the dist folder

      - name: Deploy to VPS 148.113.44.74 - OVH
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_OVH }}
          username: ${{ secrets.FTP_USER_OVH }}
          password: ${{ secrets.FTP_PASSWORD_OVH }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.click/ # The directory on the server where you want to upload the dist folder

      # goldbet.cyou

      - name: Deploy to 185.206.180.88 - PRIMA
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_PRIMA }}
          username: ${{ secrets.FTP_USER_PRIMA }}
          password: ${{ secrets.FTP_PASSWORD_PRIMA }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.cyou/ # The directory on the server where you want to upload the dist folder

      - name: Deploy to VPS 194.164.235.224 - Hostkey
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_HOSTKEY }}
          username: ${{ secrets.FTP_USER_HOSTKEY }}
          password: ${{ secrets.FTP_PASSWORD_HOSTKEY }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.cyou/ # The directory on the server where you want to upload the dist folder

      - name: Deploy to VPS 148.113.44.74 - OVH
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_OVH }}
          username: ${{ secrets.FTP_USER_OVH }}
          password: ${{ secrets.FTP_PASSWORD_OVH }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.cyou/ # The directory on the server where you want to upload the dist folder

      # goldbet.fun

      - name: Deploy to 185.206.180.88 - PRIMA
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_PRIMA }}
          username: ${{ secrets.FTP_USER_PRIMA }}
          password: ${{ secrets.FTP_PASSWORD_PRIMA }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.fun/ # The directory on the server where you want to upload the dist folder

      - name: Deploy to VPS 194.164.235.224 - Hostkey
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_HOSTKEY }}
          username: ${{ secrets.FTP_USER_HOSTKEY }}
          password: ${{ secrets.FTP_PASSWORD_HOSTKEY }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.fun/ # The directory on the server where you want to upload the dist folder

      - name: Deploy to VPS 148.113.44.74 - OVH
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_OVH }}
          username: ${{ secrets.FTP_USER_OVH }}
          password: ${{ secrets.FTP_PASSWORD_OVH }}
          local-dir: ./ # The folder containing your built project
          server-dir: /www/goldbet.fun/ # The directory on the server where you want to upload the dist folder

